# Site settings
title: Jessie Keck's Blog
email: jessie.keck@gmail.com
description: "Random thoughts about software and development process."
baseurl: ""
url: "http://jessiekeck.com"

# Build settings
markdown: kramdown
permalink: pretty
