# Site settings
title: Jessie Keck ((( Random Musings )))
email: info@jessiekeck.com
description: "Random posts about software, development process, useful techniques, and other interesting things I find in the world."
baseurl: ""
url: "http://jessiekeck.com"

# Build settings
markdown: kramdown
permalink: pretty
